AWSTemplateFormatVersion : "2010-09-09"
Description: >
  AWS Blog: Isolating network access to your AWS Cloud9 environments
  
  Sample Cloudformation template to set up interface VPC endpoints
  for use with AWS Cloud9 EC2 instance with access via AWS Systems 
  Manager. This provides interface VPC endpoints for the following
  services:
  * com.amazonaws.<region>.ssm
  * com.amazonaws.<region>.ssmmessages
  * com.amazonaws.<region>.ec2messages

Parameters: 
  ParamVpcId:
    Type: AWS::EC2::VPC::Id
    Default: "vpc-xxxxxxxxxxxxxxxxx"
    Description: "Select the VPC ID for the VPC endpoint."

  ParamSecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
    Default: 'sg-xxxxxxxxxxxxxxxxx'
    Description: >
      Select security group to associate with the VPC endpoint.

  ParamSubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Default: 'subnet-123a351e, subnet-456b351e'
    Description: "Select the subnets to associate with the VPC endpoint."

Resources:
  SSMEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      PrivateDnsEnabled: true
      SecurityGroupIds: 
        - !Ref ParamSecurityGroupId
      ServiceName: !Sub "com.amazonaws.${AWS::Region}.ssm"
      SubnetIds: 
        Ref: ParamSubnetIds
      VpcEndpointType: 'Interface'
      VpcId: 
        Ref: ParamVpcId
  
  SSMMessagesEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      PrivateDnsEnabled: true
      SecurityGroupIds: 
        - !Ref ParamSecurityGroupId
      ServiceName: !Sub "com.amazonaws.${AWS::Region}.ssmmessages"
      SubnetIds: 
        Ref: ParamSubnetIds
      VpcEndpointType: 'Interface'
      VpcId: 
        Ref: ParamVpcId

  EC2MessagesEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      PrivateDnsEnabled: true
      SecurityGroupIds: 
        - !Ref ParamSecurityGroupId
      ServiceName: !Sub "com.amazonaws.${AWS::Region}.ec2messages"
      SubnetIds: 
        Ref: ParamSubnetIds
      VpcEndpointType: 'Interface'
      VpcId: 
        Ref: ParamVpcId
