AWSTemplateFormatVersion: "2010-09-09"
Description: ""
Resources:
  Secret:
    Type: "AWS::SecretsManager::Secret"
    Properties:
      Name: "Example Secret"
      Description: "Example Description"
      KmsKeyId: "alias/aws/secretsmanager"
      GenerateSecretString:
        ExcludeLowercase: false
        ExcludeNumbers: false
        ExcludePunctuation: false
        ExcludeUppercase: false
        PasswordLength: 32
Parameters: {}
Metadata: {}
Conditions: {}
