AWSTemplateFormatVersion: "2010-09-09"
Description: ""
Resources:
  NetworkAcl:
    Type: "AWS::EC2::NetworkAcl"
    Properties:
      VpcId: "1234561234"
      Tags:
        - Key: "Name"
          Value: "Change my name"
  IngressRule0:
    Type: "AWS::EC2::NetworkAclEntry"
    Properties:
      Egress: false
      NetworkAclId:
        Ref: "NetworkAcl"
      CidrBlock: "0.0.0.0/0"
      Protocol: "tcp"
      PortRange:
        From: ""
        To: ""
      RuleNumber: "100"
      RuleAction: "allow"
  IngressRule1:
    Type: "AWS::EC2::NetworkAclEntry"
    Properties:
      Egress: false
      NetworkAclId:
        Ref: "NetworkAcl"
      CidrBlock: "0.0.0.0/0"
      Protocol: "-1"
      RuleNumber: "200"
      RuleAction: "deny"
  EgressRule0:
    Type: "AWS::EC2::NetworkAclEntry"
    Properties:
      Egress: true
      NetworkAclId:
        Ref: "NetworkAcl"
      CidrBlock: "0.0.0.0/0"
      Protocol: "tcp"
      PortRange:
        From: ""
        To: ""
      RuleNumber: "100"
      RuleAction: "allow"
  EgressRule1:
    Type: "AWS::EC2::NetworkAclEntry"
    Properties:
      Egress: true
      NetworkAclId:
        Ref: "NetworkAcl"
      CidrBlock: "0.0.0.0/0"
      Protocol: "-1"
      RuleNumber: "200"
      RuleAction: "deny"
Parameters: {}
Metadata: {}
Conditions: {}