AWSTemplateFormatVersion: "2010-09-09"
Description: ""
Resources:
  MaintenanceWindow:
    Type: "AWS::SSM::MaintenanceWindow"
    Properties:
      Name: "Patch-Manager-Maintenance-Window"
      Description: "SSM Maintenance Window to automate AWS Patch Manager tasks"
      Duration: "4"
      Cutoff: "1"
      Schedule: "cron(00 00 ? * SAT *)"
      AllowUnassociatedTargets: false
  MaintenanceWindowTarget:
    Type: "AWS::SSM::MaintenanceWindowTarget"
    Properties:
      Name: "Target-For-Patch-Manager-Maintenance-Window"
      Description: "Defines the EC2 Instance Targest for Maintenance Window: Patch-Manager-Maintenance-Window"
      ResourceType: "INSTANCE"
      WindowId:
        Ref: "MaintenanceWindow"
      Targets:
        - Key: "tag:Environment"
          Values:
            - "Production"
        - Key: "tag:Os"
          Values:
            - "Centos"
  MaintenanceWindowTask:
    Type: "AWS::SSM::MaintenanceWindowTask"
    Properties:
      Name: "Task-For-Patch-Manager-Maintenance-Window"
      Description: "Defines the Task for Maintenance Window: Patch-Manager-Maintenance-Window"
      ServiceRoleArn:
        Fn::GetAtt:
          - "MaintWindowIamRole"
          - "Arn"
      Priority: 1
      MaxErrors: 1
      MaxConcurrency: 2
      Targets:
        - Key: "WindowTargetIds"
          Values:
            - Ref: "MaintenanceWindowTarget"
      TaskType: "RUN_COMMAND"
      WindowId:
        Ref: "MaintenanceWindow"
      TaskArn: "AWS-RunPatchBaseline"
      TaskInvocationParameters:
        MaintenanceWindowRunCommandParameters:
          Parameters:
            Operation:
              - "Install"
          ServiceRoleArn:
            Fn::GetAtt:
              - "MaintWindowIamRole"
              - "Arn"
  MaintWindowIamRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: "MaintWindowIamRoleygn"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "ssm.amazonaws.com"
                - "ec2.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AmazonSSMMaintenanceWindowRole"
      Policies: []
  IamInlinePolicy:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyName: "taskRolePermissions"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action: "iam:PassRole"
            Resource:
              Fn::GetAtt:
                - "MaintWindowIamRole"
                - "Arn"
      Roles:
        - Ref: "MaintWindowIamRole"
Parameters: {}
Metadata: {}
Conditions: {}