AWSTemplateFormatVersion: "2010-09-09"
Description: "This CloudFormation template enables VPC Flow Logs, sending traffic logs to CloudWatch Logs with an IAM role for permissions."

Parameters:
  FlowLogRoleName:
    Type: String
    Default: "iamRoleFlowLogsToCloudWatchLogs"
    Description: "IAM Role name for VPC Flow Logs"

  FlowLogsRetentionDays:
    Type: Number
    Default: 30
    Description: "Number of days to retain flow logs in CloudWatch Logs"

Resources:
  # CloudWatch Log Group for VPC Flow Logs
  FlowLogsGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/vpc/${AWS::StackName}-flow-logs"
      RetentionInDays: !Ref FlowLogsRetentionDays

  # IAM Role for VPC Flow Logs
  IamRoleForFlowLogs:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref FlowLogRoleName
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "vpc-flow-logs.amazonaws.com"
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: "allow-access-to-cw-logs"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                  - "logs:DescribeLogGroups"
                  - "logs:DescribeLogStreams"
                Resource: !GetAtt FlowLogsGroup.Arn

  # VPC Flow Logs (Attaches to the VPC)
  FlowLogs:
    Type: AWS::EC2::FlowLog
    Properties:
      ResourceType: "VPC"
      ResourceId:
        Fn::ImportValue: "MyVPCStack-VPCID"  # Ensure this matches the VPC stack output
      TrafficType: "ALL"
      LogDestinationType: "cloud-watch-logs"
      LogGroupName: !Ref FlowLogsGroup
      DeliverLogsPermissionArn: !GetAtt IamRoleForFlowLogs.Arn

Outputs:
  FlowLogGroupName:
    Description: "CloudWatch Log Group for VPC Flow Logs"
    Value: !Ref FlowLogsGroup
    Export:
      Name: !Sub "${AWS::StackName}-FlowLogsGroup"

  FlowLogIAMRole:
    Description: "IAM Role used by VPC Flow Logs"
    Value: !Ref IamRoleForFlowLogs
    Export:
      Name: !Sub "${AWS::StackName}-FlowLogsRole"