AWSTemplateFormatVersion : "2010-09-09"
Description: >
  * com.amazonaws.<region>.ecs
  * com.amazonaws.<region>.ecr
  * com.amazonaws.<region>.eks
  * com.amazonaws.<region>.elasticfilesystem

Parameters: 
  ParamVpcId:
    Type: AWS::EC2::VPC::Id
    Default: "vpc-xxxxxxxxxxxxxxxxx"
    Description: "Select the VPC ID for the VPC endpoint."

  ParamSecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
    Default: 'sg-xxxxxxxxxxxxxxxxx'
    Description: >
      Select security group to associate with the VPC endpoint.

  ParamSubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Default: 'subnet-123a351e, subnet-456b351e'
    Description: "Select the subnets to associate with the VPC endpoint."

Resources:
  EcsEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      PrivateDnsEnabled: true
      SecurityGroupIds: 
        - !Ref ParamSecurityGroupId
      ServiceName: !Sub "com.amazonaws.${AWS::Region}.ecs"
      SubnetIds: 
        Ref: ParamSubnetIds
      VpcEndpointType: 'Interface'
      VpcId: 
        Ref: ParamVpcId
  
  EcrEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      PrivateDnsEnabled: true
      SecurityGroupIds: 
        - !Ref ParamSecurityGroupId
      ServiceName: !Sub "com.amazonaws.${AWS::Region}.ecr"
      SubnetIds: 
        Ref: ParamSubnetIds
      VpcEndpointType: 'Interface'
      VpcId: 
        Ref: ParamVpcId

  EksEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      PrivateDnsEnabled: true
      SecurityGroupIds: 
        - !Ref ParamSecurityGroupId
      ServiceName: !Sub "com.amazonaws.${AWS::Region}.eks"
      SubnetIds: 
        Ref: ParamSubnetIds
      VpcEndpointType: 'Interface'
      VpcId: 
        Ref: ParamVpcId

  EfsEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      PrivateDnsEnabled: true
      SecurityGroupIds: 
        - !Ref ParamSecurityGroupId
      ServiceName: !Sub "com.amazonaws.${AWS::Region}.elasticfilesystem"
      SubnetIds: 
        Ref: ParamSubnetIds
      VpcEndpointType: 'Interface'
      VpcId: 
        Ref: ParamVpcId
