AWSTemplateFormatVersion : "2010-09-09"
Description: >
  * com.amazonaws.<region>.cloudformation
  * com.amazonaws.<REGION>.logs
  * com.amazonaws.<REGION>.monitoring
  * com.amazonaws.<REGION>.synthetics
  * com.amazonaws.<REGION>.kms

Parameters: 
  ParamVpcId:
    Type: AWS::EC2::VPC::Id
    Default: "vpc-xxxxxxxxxxxxxxxxx"
    Description: "Select the VPC ID for the VPC endpoint."

  ParamSecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
    Default: 'sg-xxxxxxxxxxxxxxxxx'
    Description: >
      Select security group to associate with the VPC endpoint.

  ParamSubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Default: 'subnet-123a351e, subnet-456b351e'
    Description: "Select the subnets to associate with the VPC endpoint."

Resources:
  CloudformationEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      PrivateDnsEnabled: true
      SecurityGroupIds: 
        - !Ref ParamSecurityGroupId
      ServiceName: !Sub "com.amazonaws.${AWS::Region}.cloudformation"
      SubnetIds: 
        Ref: ParamSubnetIds
      VpcEndpointType: 'Interface'
      VpcId: 
        Ref: ParamVpcId
  
  CloudformationlogsEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      PrivateDnsEnabled: true
      SecurityGroupIds: 
        - !Ref ParamSecurityGroupId
      ServiceName: !Sub "com.amazonaws.${AWS::Region}.logs"
      SubnetIds: 
        Ref: ParamSubnetIds
      VpcEndpointType: 'Interface'
      VpcId: 
        Ref: ParamVpcId

  SynthenticsEndpoint:
      Type: AWS::EC2::VPCEndpoint
      Properties:
        PrivateDnsEnabled: true
        SecurityGroupIds: 
          - !Ref ParamSecurityGroupId
        ServiceName: !Sub "com.amazonaws.${AWS::Region}.synthetics"
        SubnetIds: 
          Ref: ParamSubnetIds
        VpcEndpointType: 'Interface'
        VpcId: 
          Ref: ParamVpcId

  MonitoringEndpoint:
      Type: AWS::EC2::VPCEndpoint
      Properties:
        PrivateDnsEnabled: true
        SecurityGroupIds: 
          - !Ref ParamSecurityGroupId
        ServiceName: !Sub "com.amazonaws.${AWS::Region}.monitoring"
        SubnetIds: 
          Ref: ParamSubnetIds
        VpcEndpointType: 'Interface'
        VpcId: 
          Ref: ParamVpcId

  KmsEndpoint:
      Type: AWS::EC2::VPCEndpoint
      Properties:
        PrivateDnsEnabled: true
        SecurityGroupIds: 
          - !Ref ParamSecurityGroupId
        ServiceName: !Sub "com.amazonaws.${AWS::Region}.kms"
        SubnetIds: 
          Ref: ParamSubnetIds
        VpcEndpointType: 'Interface'
        VpcId: 
          Ref: ParamVpcId

