---
AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Provision AWS Managed Active Directory
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: Active Directory Settings
      Parameters:
      - DomainName
      - MicrosoftADShortName
      - MicrosoftADPW
      - Edition
      - CreateAlias
      - EnableSingleSignOn
    - Label:
        default: VPC Networking Settings
      Parameters:
      - VPCID
      - PrivateSubnet1
      - PrivateSubnet2
    ParameterLabels:
      DomainName:
        default: Name
      MicrosoftADShortName:
        default: Short Name
      MicrosoftADPW:
        default: Active Directory Admin Password
      Edition:
        default: Edition
      CreateAlias:
        default: Create Alias
      EnableSingleSignOn:
        default: Enable Single Sign On
      VPCID:
        default: VPC ID
      PrivateSubnet1:
        default: Private Subnet 1
      PrivateSubnet2:
        default: Private Subnet 2

Parameters:
  Edition:
    Description: >
      The AWS Microsoft AD edition. Valid values include Standard and
      Enterprise. The default is Enterprise.
    Type: String
    Default: Enterprise
    AllowedValues:
    - Standard
    - Enterprise
  DomainName:
    Description: >
      The fully qualified name for the Microsoft Active Directory
      in AWS, such as corp.example.com. The name doesn't need to be
      publicly resolvable; it will resolve inside your VPC only.
    Type: String
    Default: corp.example.com
  MicrosoftADShortName:
    Description: >
      The NetBIOS name for your domain, such as CORP. If you don't specify
      a value, AWS Directory Service uses the first part of your directory
      DNS server name. For example, if your directory DNS server name is
      corp.example.com, AWS Directory Service specifies CORP for the NetBIOS
      name.
    Type: String
    Default: corp
  EnableSingleSignOn:
    Description: >
      Whether to enable single sign-on for a Microsoft Active
      Directory in AWS. Single sign-on allows users in your
      directory to access certain AWS services from a computer
      joined to the directory without having to enter their
      credentials separately. If you don't specify a value,
      AWS CloudFormation disables single sign-on by default.
      If enabling SSO, then "Create Alias" need to be set to true.
    Type: String
    AllowedValues:
    - 'true'
    - 'false'
    Default: 'false'
  CreateAlias:
    Description: >
      A unique alias to assign to the Microsoft Active Directory in AWS.
      AWS Directory Service uses the alias to construct the access URL for
      the directory, such as http://alias.awsapps.com. By default, AWS
      CloudFormation does not create an alias.
    Type: String
    AllowedValues:
    - 'true'
    - 'false'
    Default: 'false'
  MicrosoftADPW:
    Description: >
      The password for the default administrative user, Admin.
    Type: String
    NoEcho: true
    Default: Pass@w0rd
  PrivateSubnet1:
    Description: >
      A subnet within the selected VPC. Each subnet must be in
      different Availability Zones (AZs). AWS Directory Service
      creates a directory server and a DNS server in each subnet.
    Type: AWS::EC2::Subnet::Id
  PrivateSubnet2:
    Description: >
      A second subnet in same VPC that is in different AZ.
      Each subnet must be in different Availability Zones (AZs).
      AWS Directory Service creates a directory server and a DNS
      server in each subnet.
    Type: AWS::EC2::Subnet::Id
  VPCID:
    Description: >
      The VPC ID in which to create the Microsoft Active Directory server.
    Type: AWS::EC2::VPC::Id

Conditions:
  cAlias: !Equals [ !Ref CreateAlias, 'true' ]

Resources:
  MSDirectory:
    Type: AWS::DirectoryService::MicrosoftAD
    Properties:
      CreateAlias: !Ref CreateAlias
      Edition: !Ref Edition
      EnableSso: !Ref EnableSingleSignOn
      Name: !Ref DomainName
      Password: !Ref MicrosoftADPW
      ShortName: !Ref MicrosoftADShortName
      VpcSettings:
        SubnetIds:
        - !Ref PrivateSubnet1
        - !Ref PrivateSubnet2
        VpcId: !Ref VPCID

Outputs:
  DirectoryID:
    Description: ID of the MS Directory
    Value: !Ref MSDirectory
  PrimaryDNS:
    Description: DNS IPs of the MS Directory
    Value: !Select [ '0', !GetAtt MSDirectory.DnsIpAddresses ]
  SecondaryDNS:
    Description: DNS IPs of the MSDirectory
    Value: !Select [ '1', !GetAtt MSDirectory.DnsIpAddresses ]
  DirectoryAlias:
    Description: URL for the alias
    Condition: cAlias
    Value: !GetAtt MSDirectory.Alias