AWSTemplateFormatVersion: "2010-09-09"
Description: ""
Resources:
  DataLifecycleManager:
    Type: "AWS::DLM::LifecyclePolicy"
    Properties:
      Description: "Data Lifecycle Manager Policy"
      State: "ENABLED"
      ExecutionRoleArn:
        Fn::GetAtt:
          - "DlmIamRoleDataLifecycleManager"
          - "Arn"
      PolicyDetails:
        ResourceTypes:
          - "INSTANCE"
        TargetTags:
          - Key: "Backup"
            Value: "True"
        Schedules:
          - Name: "Snapshot Schedule"
            TagsToAdd: []
            CreateRule:
              Interval: 24
              IntervalUnit: "HOURS"
              Times:
                - "00:00"
            RetainRule:
              Interval: 1
              IntervalUnit: "MONTHS"
            CopyTags: true
  DlmIamRoleDataLifecycleManager:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "dlm.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns: []
      Policies:
        - PolicyName: "DlmPermissions"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "ec2:CreateSnapshot"
                  - "ec2:CreateSnapshots"
                  - "ec2:DeleteSnapshot"
                  - "ec2:DescribeVolumes"
                  - "ec2:DescribeInstances"
                  - "ec2:DescribeSnapshots"
                Resource: "*"
              - Effect: "Allow"
                Action:
                  - "ec2:CreateTags"
                Resource: "arn:aws:ec2:*::snapshot/*"
Parameters: {}
Metadata: {}
Conditions: {}