AWSTemplateFormatVersion: 2010-09-09  
Description: Template to create an EC2 instance and enable SSH  
Parameters:   
  KeyName:  
    Description: Name of SSH KeyPair  
    Type: 'AWS::EC2::KeyPair::KeyName'  
    ConstraintDescription: Provide the name of an existing SSH key pair  
Resources:  
  InstanceSecurityGroup:  
    Type: 'AWS::EC2::SecurityGroup'  
    Properties:  
      GroupDescription: Enable SSH access via port 22 and HTTP access via port 80  
      SecurityGroupIngress:   
        - IpProtocol: tcp  
          FromPort: 22  
          ToPort: 22  
          CidrIp: 0.0.0.0/0   
        - IpProtocol: tcp  
          FromPort: 80  
          ToPort: 80  
          CidrIp: 0.0.0.0/0  
  MyEC2Instance:  
    Type: 'AWS::EC2::Instance'  
    Properties:  
      InstanceType: t2.micro  
      ImageId: ami-009d6802948d06e52  
      KeyName: !Ref KeyName  
      SecurityGroups:   
        - !Ref InstanceSecurityGroup  
      Tags:  
        - Key: Name  
          Value: My CF Instance  
Outputs:   
  InstanceID:  
    Description: The Instance ID  
    Value: !Ref MyEC2Instance  
  PublicIP:  
    Description: The public IP of the instance  
    Value: !GetAtt [ MyEC2Instance, PublicIp ]