AWSTemplateFormatVersion : "2010-09-09"
Description: >
  * com.amazonaws.<region>.ec2
  * com.amazonaws.<region>.autoscaling
  * com.amazonaws.<region>.imagebuilder

Parameters: 
  ParamVpcId:
    Type: AWS::EC2::VPC::Id
    Default: "vpc-xxxxxxxxxxxxxxxxx"
    Description: "Select the VPC ID for the VPC endpoint."

  ParamSecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
    Default: 'sg-xxxxxxxxxxxxxxxxx'
    Description: >
      Select security group to associate with the VPC endpoint.

  ParamSubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Default: 'subnet-123a351e, subnet-456b351e'
    Description: "Select the subnets to associate with the VPC endpoint."

Resources:
  Ec2Endpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      PrivateDnsEnabled: true
      SecurityGroupIds: 
        - !Ref ParamSecurityGroupId
      ServiceName: !Sub "com.amazonaws.${AWS::Region}.ec2"
      SubnetIds: 
        Ref: ParamSubnetIds
      VpcEndpointType: 'Interface'
      VpcId: 
        Ref: ParamVpcId
  
  AutoScalingEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      PrivateDnsEnabled: true
      SecurityGroupIds: 
        - !Ref ParamSecurityGroupId
      ServiceName: !Sub "com.amazonaws.${AWS::Region}.autoscaling"
      SubnetIds: 
        Ref: ParamSubnetIds
      VpcEndpointType: 'Interface'
      VpcId: 
        Ref: ParamVpcId

  ImageBuilderEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      PrivateDnsEnabled: true
      SecurityGroupIds: 
        - !Ref ParamSecurityGroupId
      ServiceName: !Sub "com.amazonaws.${AWS::Region}.imagebuilder"
      SubnetIds: 
        Ref: ParamSubnetIds
      VpcEndpointType: 'Interface'
      VpcId: 
        Ref: ParamVpcId